name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cache node modules for faster installs
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 3. Use Node.js (choose version that matches your project)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 4. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 5. Lint
      - name: Lint code
        run: npm run lint

      # 6. Type-check (if using TypeScript)
      - name: Type-check
        run: npm run typecheck

      # 7. Run tests
      - name: Run tests
        run: npm test

      # 8. Build
      - name: Build production bundle
        run: npm run build

